artifact_location: file:///C:/Users/iniqg/Downloads/defect-inspection-system/defect-inspection-system/runs/mlflow/273147313027672267
creation_time: 1788410777118
experiment_id: '273147313027672267'
last_update_time: 1788410777118
lifecycle_stage: active
name: runs/train
